# Generated by Django 4.2.1 on 2024-08-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='action_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='agility',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='buff_duration',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='debuff_duration',
            field=models.IntegerField(default=-37),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='knowledge',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='magical_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='move_speed',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='character',
            name='physical_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='power_grade',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='character',
            name='resourcefulness',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_casting_speed',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='will',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='health',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='character',
            name='vigor',
            field=models.IntegerField(default=11),
        ),
    ]
